site_name: Eric Yang's Notes

site_author: Yalin(Eric) Yang

# Repository
repo_name: gisyaliny/Notes
repo_url: https://gisyaliny.github.io/Notes/

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://gisyaliny.github.io/
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/c17hawke
    - icon: fontawesome/brands/linkedin
      link: www.linkedin.com/in/gisyaliny
    # - icon: fontawesome/brands/instagram
    #   link: https://www.instagram.com/c17hawke/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://gisyaliny.github.io/"  target="_blank" rel="noopener">Yalin Yang</a>