site_name: Yalin(Eric) Yang's Projects
theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
plugins:
  - search
nav:
  - Introduction: "index.md"
  - Projects:
    - Recommender System: "pages/Recommender-System/Recommender-System.md"
  - About: "pages/about.md"
